apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: avinashdesireddy/go-webapp:1.0.2 # {"$imagepolicy": "flux-system:go-webapp"}
