name: Build Webapp - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd apps/go-webapp/src
        docker build . --file Dockerfile --tag avinashdesireddy/go-webapp:$(date +%s)
